global.ROLE_HARVESTER = 'Harvester'
global.ROLE_HAULER = 'Hauler'
global.ROLE_WORKER = 'Worker'

global.TERRAIN_WALL  = 'wall'
global.TERRAIN_PLAIN = 'plain'
global.TERRAIN_SWAMP = 'swamp'

const toString = {
}

toString[OK] = 'OK'
toString[ERR_NOT_OWNER] = 'ERR_NOT_OWNER'
toString[ERR_NO_PATH] = 'ERR_NO_PATH'
toString[ERR_NAME_EXISTS] = 'ERR_NAME_EXISTS'
toString[ERR_BUSY] = 'ERR_BUSY'
toString[ERR_NOT_FOUND] = 'ERR_NOT_FOUND'
toString[ERR_NOT_ENOUGH_ENERGY] = 'ERR_NOT_ENOUGH_ENERGY'
toString[ERR_NOT_ENOUGH_RESOURCES] = 'ERR_NOT_ENOUGH_RESOURCES'
toString[ERR_INVALID_TARGET] = 'ERR_INVALID_TARGET'
toString[ERR_FULL] = 'ERR_FULL'
toString[ERR_NOT_IN_RANGE] = 'ERR_NOT_IN_RANGE'
toString[ERR_INVALID_ARGS] = 'ERR_INVALID_ARGS'
toString[ERR_TIRED] = 'ERR_TIRED'
toString[ERR_NO_BODYPART] = 'ERR_NO_BODYPART'
toString[ERR_NOT_ENOUGH_EXTENSIONS] = 'ERR_NOT_ENOUGH_EXTENSIONS'
toString[ERR_RCL_NOT_ENOUGH] = 'ERR_RCL_NOT_ENOUGH'
toString[ERR_GCL_NOT_ENOUGH] = 'ERR_GCL_NOT_ENOUGH'

exports.toString = toString
